name: CI

on:
  push:
    branches: [ bazelbuild ]
  pull_request:
    branches: [ bazelbuild ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build //...
      - run: bazel test //...
